# Generated by Django 6.0.5 on 2026-05-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('ocupacion', models.CharField(max_length=100)),
                ('documento_identidad', models.CharField(max_length=30, unique=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('edad', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('ciudad_nacimiento', models.CharField(max_length=100)),
                ('estado_nacimiento', models.CharField(max_length=100)),
                ('pais_nacimiento', models.CharField(choices=[('Mexico', 'México'), ('Argentina', 'Argentina'), ('Colombia', 'Colombia'), ('Chile', 'Chile'), ('Peru', 'Perú'), ('España', 'España'), ('USA', 'Estados Unidos')], max_length=50)),
                ('direccion', models.CharField(max_length=255)),
                ('colonia_barrio', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=20)),
                ('telefono_movil', models.CharField(max_length=20)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('grupo_sanguineo', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('alergias', models.CharField(blank=True, help_text='Si no tiene alergias, escriba "Ninguna".', max_length=255)),
                ('tiene_padecimiento_fisico', models.BooleanField(default=False)),
                ('descripcion_padecimiento_fisico', models.TextField(blank=True)),
                ('bajo_tratamiento_medico', models.BooleanField(default=False)),
                ('descripcion_tratamiento_medico', models.TextField(blank=True)),
                ('toma_medicamentos', models.BooleanField(default=False)),
                ('descripcion_medicamentos', models.TextField(blank=True, help_text='Incluya nombre del medicamento y forma de suministro.')),
                ('tiene_seguro_medico', models.BooleanField(default=False)),
                ('descripcion_seguro_medico', models.CharField(blank=True, max_length=255)),
                ('contacto_nombre', models.CharField(max_length=100)),
                ('contacto_apellido', models.CharField(max_length=100)),
                ('contacto_parentesco', models.CharField(choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Hermano/a', 'Hermano/a'), ('Esposo/a', 'Esposo/a'), ('Hijo/a', 'Hijo/a'), ('Pareja', 'Pareja'), ('Amigo/a', 'Amigo/a'), ('Otro', 'Otro')], max_length=20)),
                ('contacto_direccion', models.CharField(max_length=255)),
                ('contacto_colonia_barrio', models.CharField(max_length=100)),
                ('contacto_codigo_postal', models.CharField(max_length=20)),
                ('contacto_telefono_movil', models.CharField(max_length=20)),
                ('contacto2_nombre', models.CharField(blank=True, max_length=100)),
                ('contacto2_apellido', models.CharField(blank=True, max_length=100)),
                ('contacto2_telefono_movil', models.CharField(blank=True, max_length=20)),
                ('modelo_vehiculo', models.CharField(max_length=100)),
                ('placa_vehiculo', models.CharField(max_length=20, unique=True)),
                ('documento_vehiculo', models.FileField(upload_to='documentos_vehiculo/')),
                ('documento_identificacion', models.FileField(upload_to='identificaciones/')),
                ('acepta_liberacion_responsabilidad', models.BooleanField(default=False)),
                ('acepta_tratamiento_datos', models.BooleanField(default=False)),
                ('acepta_permiso_fotografias', models.BooleanField(default=False)),
                ('fecha_aceptacion_legal', models.DateTimeField(blank=True, null=True)),
                ('firma_conformidad', models.FileField(blank=True, null=True, upload_to='firmas/')),
                ('registro_completo', models.BooleanField(default=False)),
            ],
        ),
    ]
