# Generated by Django 6.0.5 on 2026-05-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('ocupacion', models.CharField(max_length=100)),
                ('documento_identidad', models.CharField(max_length=30, unique=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('edad', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('ciudad_nacimiento', models.CharField(max_length=100)),
                ('estado_nacimiento', models.CharField(max_length=100)),
                ('pais_nacimiento', models.CharField(choices=[('Mexico', 'México'), ('Argentina', 'Argentina'), ('Colombia', 'Colombia'), ('Chile', 'Chile'), ('Peru', 'Perú'), ('España', 'España'), ('USA', 'Estados Unidos')], max_length=50)),
                ('direccion', models.CharField(max_length=255)),
                ('colonia_barrio', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=20)),
                ('telefono_movil', models.CharField(max_length=20)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
